### ISSUE TITLE
Compile instructions

### ISSUE THREAD

**Issue by bogdanr** [kritzikratzi/ofxAvCodec#12]
How do I compile this on Linux?
I think I need it for [Oscilloscope](https://github.com/kritzikratzi/Oscilloscope)

**Comment by kritzikratzi** [comment]
not sure, i haven't done it in ages. but i have set up a linux drive last week and i'm hoping to start use it soon. 
^^

the basic idea is: 

1. look at the instructions for compiling ffmpeg+openh264 and see if you can make a linux library: https://github.com/kritzikratzi/ofxAvCodec/tree/master/ffmpeg_src you'll have to do this yourself if you care which decoders and encoders are enabled (this is important if you care about the licensing). pay special attention to the commit hashes that i list and use exactly those, otherwise you will get incompatibilities! 
2. if everything goes well you have a bunch of dynamic libs for 32 and/or (ideally and) 64bit at the end
3. download openframeworks and follow the setup instructions (you run openframeworks/scripts/linux/...../install-dependencies.sh, it only does a few apt-gets)
4. clone the oscilloscope repository into openframeworks/apps/myApps/oscilloscope
5. drop your so files in `oscilloscope/addons/ofxAvCodec/libs/avcodec/lib/linux`
6. in the oscilloscope folder, run `make -j8 && make run`. then keep fixing errors until something interresting happens


the first time setup can be a bit alienating. but this is meant as an application for users, not for devs, i hope you understand :)
